// Code generated by protoc-gen-go.
// source: route.proto
// DO NOT EDIT!

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Points are represented as latitude-longitude pairs in the E7 representation
// (degrees multiplied by 10**7 and rounded to the nearest integer).
// Latitudes should be in the range +/- 90 degrees and longitude should be in
// the range +/- 180 degrees (inclusive).
type Point struct {
	Latitude  int32 `protobuf:"varint,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude int32 `protobuf:"varint,2,opt,name=longitude" json:"longitude,omitempty"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Point) GetLatitude() int32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Point) GetLongitude() int32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

// A latitude-longitude rectangle, represented as two diagonally opposite
// points "lo" and "hi".
type Rectangle struct {
	// One corner of the rectangle.
	Lo *Point `protobuf:"bytes,1,opt,name=lo" json:"lo,omitempty"`
	// The other corner of the rectangle.
	Hi *Point `protobuf:"bytes,2,opt,name=hi" json:"hi,omitempty"`
}

func (m *Rectangle) Reset()                    { *m = Rectangle{} }
func (m *Rectangle) String() string            { return proto.CompactTextString(m) }
func (*Rectangle) ProtoMessage()               {}
func (*Rectangle) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Rectangle) GetLo() *Point {
	if m != nil {
		return m.Lo
	}
	return nil
}

func (m *Rectangle) GetHi() *Point {
	if m != nil {
		return m.Hi
	}
	return nil
}

// A feature names something at a given point.
//
// If a feature could not be named, the name is empty.
type Feature struct {
	// The name of the feature.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// The point where the feature is detected.
	Location *Point `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
}

func (m *Feature) Reset()                    { *m = Feature{} }
func (m *Feature) String() string            { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()               {}
func (*Feature) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Feature) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Feature) GetLocation() *Point {
	if m != nil {
		return m.Location
	}
	return nil
}

// A RouteNote is a message sent while at a given point.
type RouteNote struct {
	// The location from which the message is sent.
	Location *Point `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	// The message to be sent.
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *RouteNote) Reset()                    { *m = RouteNote{} }
func (m *RouteNote) String() string            { return proto.CompactTextString(m) }
func (*RouteNote) ProtoMessage()               {}
func (*RouteNote) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *RouteNote) GetLocation() *Point {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *RouteNote) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// A RouteSummary is received in response to a RecordRoute rpc.
//
// It contains the number of individual points received, the number of
// detected features, and the total distance covered as the cumulative sum of
// the distance between each point.
type RouteSummary struct {
	// The number of points received.
	PointCount int32 `protobuf:"varint,1,opt,name=point_count,json=pointCount" json:"point_count,omitempty"`
	// The number of known features passed while traversing the route.
	FeatureCount int32 `protobuf:"varint,2,opt,name=feature_count,json=featureCount" json:"feature_count,omitempty"`
	// The distance covered in metres.
	Distance int32 `protobuf:"varint,3,opt,name=distance" json:"distance,omitempty"`
	// The duration of the traversal in seconds.
	ElapsedTime int32 `protobuf:"varint,4,opt,name=elapsed_time,json=elapsedTime" json:"elapsed_time,omitempty"`
}

func (m *RouteSummary) Reset()                    { *m = RouteSummary{} }
func (m *RouteSummary) String() string            { return proto.CompactTextString(m) }
func (*RouteSummary) ProtoMessage()               {}
func (*RouteSummary) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *RouteSummary) GetPointCount() int32 {
	if m != nil {
		return m.PointCount
	}
	return 0
}

func (m *RouteSummary) GetFeatureCount() int32 {
	if m != nil {
		return m.FeatureCount
	}
	return 0
}

func (m *RouteSummary) GetDistance() int32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *RouteSummary) GetElapsedTime() int32 {
	if m != nil {
		return m.ElapsedTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Point)(nil), "api.Point")
	proto.RegisterType((*Rectangle)(nil), "api.Rectangle")
	proto.RegisterType((*Feature)(nil), "api.Feature")
	proto.RegisterType((*RouteNote)(nil), "api.RouteNote")
	proto.RegisterType((*RouteSummary)(nil), "api.RouteSummary")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Route service

type RouteClient interface {
	// A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	GetFeature(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Feature, error)
	// A server-to-client streaming RPC.
	//
	// Obtains the Features available within the given Rectangle.  Results are
	// streamed rather than returned at once (e.g. in a response message with a
	// repeated field), as the rectangle may cover a large area and contain a
	// huge number of features.
	ListFeatures(ctx context.Context, in *Rectangle, opts ...grpc.CallOption) (Route_ListFeaturesClient, error)
	// A client-to-server streaming RPC.
	//
	// Accepts a stream of Points on a route being traversed, returning a
	// RouteSummary when traversal is completed.
	RecordRoute(ctx context.Context, opts ...grpc.CallOption) (Route_RecordRouteClient, error)
	// A Bidirectional streaming RPC.
	//
	// Accepts a stream of RouteNotes sent while a route is being traversed,
	// while receiving other RouteNotes (e.g. from other users).
	RouteChat(ctx context.Context, opts ...grpc.CallOption) (Route_RouteChatClient, error)
}

type routeClient struct {
	cc *grpc.ClientConn
}

func NewRouteClient(cc *grpc.ClientConn) RouteClient {
	return &routeClient{cc}
}

func (c *routeClient) GetFeature(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Feature, error) {
	out := new(Feature)
	err := grpc.Invoke(ctx, "/api.Route/GetFeature", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routeClient) ListFeatures(ctx context.Context, in *Rectangle, opts ...grpc.CallOption) (Route_ListFeaturesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Route_serviceDesc.Streams[0], c.cc, "/api.Route/ListFeatures", opts...)
	if err != nil {
		return nil, err
	}
	x := &routeListFeaturesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Route_ListFeaturesClient interface {
	Recv() (*Feature, error)
	grpc.ClientStream
}

type routeListFeaturesClient struct {
	grpc.ClientStream
}

func (x *routeListFeaturesClient) Recv() (*Feature, error) {
	m := new(Feature)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *routeClient) RecordRoute(ctx context.Context, opts ...grpc.CallOption) (Route_RecordRouteClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Route_serviceDesc.Streams[1], c.cc, "/api.Route/RecordRoute", opts...)
	if err != nil {
		return nil, err
	}
	x := &routeRecordRouteClient{stream}
	return x, nil
}

type Route_RecordRouteClient interface {
	Send(*Point) error
	CloseAndRecv() (*RouteSummary, error)
	grpc.ClientStream
}

type routeRecordRouteClient struct {
	grpc.ClientStream
}

func (x *routeRecordRouteClient) Send(m *Point) error {
	return x.ClientStream.SendMsg(m)
}

func (x *routeRecordRouteClient) CloseAndRecv() (*RouteSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(RouteSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *routeClient) RouteChat(ctx context.Context, opts ...grpc.CallOption) (Route_RouteChatClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Route_serviceDesc.Streams[2], c.cc, "/api.Route/RouteChat", opts...)
	if err != nil {
		return nil, err
	}
	x := &routeRouteChatClient{stream}
	return x, nil
}

type Route_RouteChatClient interface {
	Send(*RouteNote) error
	Recv() (*RouteNote, error)
	grpc.ClientStream
}

type routeRouteChatClient struct {
	grpc.ClientStream
}

func (x *routeRouteChatClient) Send(m *RouteNote) error {
	return x.ClientStream.SendMsg(m)
}

func (x *routeRouteChatClient) Recv() (*RouteNote, error) {
	m := new(RouteNote)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Route service

type RouteServer interface {
	// A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	GetFeature(context.Context, *Point) (*Feature, error)
	// A server-to-client streaming RPC.
	//
	// Obtains the Features available within the given Rectangle.  Results are
	// streamed rather than returned at once (e.g. in a response message with a
	// repeated field), as the rectangle may cover a large area and contain a
	// huge number of features.
	ListFeatures(*Rectangle, Route_ListFeaturesServer) error
	// A client-to-server streaming RPC.
	//
	// Accepts a stream of Points on a route being traversed, returning a
	// RouteSummary when traversal is completed.
	RecordRoute(Route_RecordRouteServer) error
	// A Bidirectional streaming RPC.
	//
	// Accepts a stream of RouteNotes sent while a route is being traversed,
	// while receiving other RouteNotes (e.g. from other users).
	RouteChat(Route_RouteChatServer) error
}

func RegisterRouteServer(s *grpc.Server, srv RouteServer) {
	s.RegisterService(&_Route_serviceDesc, srv)
}

func _Route_GetFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Point)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouteServer).GetFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Route/GetFeature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouteServer).GetFeature(ctx, req.(*Point))
	}
	return interceptor(ctx, in, info, handler)
}

func _Route_ListFeatures_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Rectangle)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RouteServer).ListFeatures(m, &routeListFeaturesServer{stream})
}

type Route_ListFeaturesServer interface {
	Send(*Feature) error
	grpc.ServerStream
}

type routeListFeaturesServer struct {
	grpc.ServerStream
}

func (x *routeListFeaturesServer) Send(m *Feature) error {
	return x.ServerStream.SendMsg(m)
}

func _Route_RecordRoute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RouteServer).RecordRoute(&routeRecordRouteServer{stream})
}

type Route_RecordRouteServer interface {
	SendAndClose(*RouteSummary) error
	Recv() (*Point, error)
	grpc.ServerStream
}

type routeRecordRouteServer struct {
	grpc.ServerStream
}

func (x *routeRecordRouteServer) SendAndClose(m *RouteSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *routeRecordRouteServer) Recv() (*Point, error) {
	m := new(Point)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Route_RouteChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RouteServer).RouteChat(&routeRouteChatServer{stream})
}

type Route_RouteChatServer interface {
	Send(*RouteNote) error
	Recv() (*RouteNote, error)
	grpc.ServerStream
}

type routeRouteChatServer struct {
	grpc.ServerStream
}

func (x *routeRouteChatServer) Send(m *RouteNote) error {
	return x.ServerStream.SendMsg(m)
}

func (x *routeRouteChatServer) Recv() (*RouteNote, error) {
	m := new(RouteNote)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Route_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Route",
	HandlerType: (*RouteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeature",
			Handler:    _Route_GetFeature_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListFeatures",
			Handler:       _Route_ListFeatures_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RecordRoute",
			Handler:       _Route_RecordRoute_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "RouteChat",
			Handler:       _Route_RouteChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "route.proto",
}

func init() { proto.RegisterFile("route.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 391 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x52, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0xae, 0xfb, 0x43, 0x9b, 0x93, 0x80, 0xc4, 0xb9, 0x21, 0x8a, 0x90, 0x80, 0x20, 0x41, 0xaf,
	0xa2, 0xd0, 0x3e, 0x01, 0xad, 0x80, 0x1b, 0x40, 0x55, 0xb6, 0xfb, 0xca, 0x73, 0xbc, 0xc4, 0x52,
	0x6c, 0x47, 0x89, 0x73, 0xb1, 0xe7, 0xd8, 0x4b, 0xed, 0xb1, 0xa6, 0xd8, 0x49, 0xd7, 0x55, 0xdb,
	0x9d, 0xcf, 0xf9, 0x7e, 0xec, 0xf3, 0xf9, 0x80, 0xdf, 0xe8, 0xce, 0xf0, 0xa4, 0x6e, 0xb4, 0xd1,
	0x38, 0xa3, 0xb5, 0x88, 0x7f, 0xc2, 0xe2, 0xa0, 0x85, 0x32, 0x18, 0xc1, 0xaa, 0xa2, 0x46, 0x98,
	0x2e, 0xe7, 0x21, 0xf9, 0x4c, 0xd6, 0x8b, 0xec, 0x54, 0xe3, 0x47, 0xf0, 0x2a, 0xad, 0x0a, 0x07,
	0x4e, 0x2d, 0xf8, 0xd4, 0x88, 0xf7, 0xe0, 0x65, 0x9c, 0x19, 0xaa, 0x8a, 0x8a, 0x63, 0x04, 0xd3,
	0x4a, 0x5b, 0x03, 0x7f, 0x03, 0x09, 0xad, 0x45, 0x62, 0xed, 0xb3, 0x69, 0xa5, 0x7b, 0xac, 0x14,
	0x56, 0x7f, 0x81, 0x95, 0x22, 0xfe, 0x05, 0xcb, 0xdf, 0x9c, 0x9a, 0xae, 0xe1, 0x88, 0x30, 0x57,
	0x54, 0xba, 0x57, 0x78, 0x99, 0x3d, 0xe3, 0x37, 0x58, 0x55, 0x9a, 0x51, 0x23, 0xb4, 0x7a, 0xc1,
	0xe0, 0x84, 0xc5, 0xff, 0xc0, 0xcb, 0xfa, 0x11, 0xff, 0x6b, 0xf3, 0x5c, 0x44, 0x5e, 0x17, 0x61,
	0x08, 0x4b, 0xc9, 0xdb, 0x96, 0x16, 0x6e, 0x38, 0x2f, 0x1b, 0xcb, 0xf8, 0x9e, 0x40, 0x60, 0xfd,
	0xae, 0x3a, 0x29, 0x69, 0x73, 0x87, 0x9f, 0xc0, 0xaf, 0x7b, 0xf5, 0x91, 0xe9, 0x4e, 0x99, 0x21,
	0x28, 0xb0, 0xad, 0x7d, 0xdf, 0xc1, 0xaf, 0xf0, 0xf6, 0xd6, 0xcd, 0x31, 0x50, 0x5c, 0x5c, 0xc1,
	0xd0, 0x74, 0xa4, 0x08, 0x56, 0xb9, 0x68, 0x0d, 0x55, 0x8c, 0x87, 0x33, 0x97, 0xf5, 0x58, 0xe3,
	0x17, 0x08, 0x78, 0x45, 0xeb, 0x96, 0xe7, 0x47, 0x23, 0x24, 0x0f, 0xe7, 0x16, 0xf7, 0x87, 0xde,
	0xb5, 0x90, 0x7c, 0xf3, 0x40, 0x60, 0x61, 0x5f, 0x85, 0x6b, 0x80, 0x3f, 0xdc, 0x8c, 0xc1, 0x9d,
	0x4d, 0x17, 0x05, 0xf6, 0x3c, 0x20, 0xf1, 0x04, 0x53, 0x08, 0xfe, 0x8a, 0x76, 0xa4, 0xb6, 0xf8,
	0xce, 0xe2, 0xa7, 0x7f, 0xbb, 0xe4, 0xa7, 0x04, 0x53, 0xf0, 0x33, 0xce, 0x74, 0x93, 0xbb, 0xab,
	0xce, 0xcd, 0xdf, 0x3b, 0xf1, 0x59, 0x30, 0xf1, 0x64, 0x4d, 0xf0, 0xc7, 0x10, 0xfe, 0xbe, 0xa4,
	0x66, 0xbc, 0x60, 0xfc, 0x8c, 0xe8, 0xa2, 0xee, 0x05, 0x29, 0xd9, 0x7d, 0x87, 0x0f, 0x4c, 0xcb,
	0xa4, 0xdc, 0xb2, 0x24, 0xa7, 0x5c, 0x6a, 0x95, 0x14, 0x4d, 0xcd, 0x7a, 0xea, 0x0e, 0x2c, 0xf7,
	0xd0, 0xaf, 0xea, 0x81, 0xdc, 0xbc, 0xb1, 0x3b, 0xbb, 0x7d, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x44,
	0xf2, 0x2d, 0x04, 0xc2, 0x02, 0x00, 0x00,
}
